name: Psalm

on: [push]

jobs:
  psalm:
    name: psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: Run psalm
        run: ./vendor/bin/psalm --output-format=github